server:
  port: 8080
  host: localhost

database:
  host: localhost
  port: 5432
  user: postgres
  password: your_password
  dbname: quran_search
  sslmode: disable

search:
  max_results: 20
  highlight: true 